// @ai-module: Shared Type Contracts
// @ai-role: Single source of truth for all domain types shared across stores, hooks, and components.
//           Every type here has a "contract" annotation describing which system owns/generates that data.
// @ai-dependencies: None — this is the leaf module. All other modules import from here; nothing imports into here.

// [AI-STRICT] DO NOT add runtime logic to this file. Types and type aliases only.
// [AI-STRICT] DO NOT remove or rename existing types without updating every store, hook, and component that references them.

// @ai-contract: AgentRole is the canonical identity for the three-agent swarm.
//               Valid roles: 'tech-lead' (orchestrator), 'dev' (implementor), 'qa' (verifier).
//               Used as keys in AgentStatuses and ActiveActivities records — all three roles must always be present.
export type AgentRole = 'tech-lead' | 'dev' | 'qa';

// @ai-contract: Managed by Nanobot orchestration engine (agentStore.updateAgentStatus).
//               Valid state machine transitions: idle -> thinking -> working -> idle.
//               When the real backend is connected, this is driven by OpenHands SDK agent lifecycle events.
export type AgentStatus = 'idle' | 'thinking' | 'working';

// @ai-contract: Each AgentMessage is generated by an agent during a run (mock: agentSimulation.ts; real: WebSocket 'agent:message' events).
//               The `id` field is assigned by agentStore.addMessage — callers must omit it (use Omit<AgentMessage, 'id'>).
//               The `timestamp` field is also set by the store; callers must not pass it.
export type AgentMessage = {
  id: string;
  agent: AgentRole;
  agentLabel: string;
  content: string;
  timestamp: string;
};

// @ai-contract: TaskStatus is driven by agentStore.updateTask. Valid transitions: pending -> in-progress -> completed.
//               Tasks are never deleted; they only move forward in status.
export type TaskStatus = 'completed' | 'in-progress' | 'pending';

// @ai-contract: Task objects originate from mockData.initialTasks (static seed).
//               When the real backend is connected, tasks will arrive via WebSocket 'task:update' events.
//               The orchestrator (tech-lead agent) owns task creation and status progression.
export type Task = {
  id: string;
  label: string;
  status: TaskStatus;
  agent: AgentRole;
  subtasks?: string[];
};

// @ai-contract: LogLineType controls ANSI color rendering in TerminalPanel.
//               Each type maps to a specific ANSI escape sequence in the formatLine() function.
//               'cursor' is a special type used for the blinking terminal prompt ($ _).
//               'blank' renders an empty line — do not use 'output' with an empty string instead.
export type LogLineType =
  | 'command'
  | 'success'
  | 'warn'
  | 'error'
  | 'info'
  | 'output'
  | 'cursor'
  | 'blank';

// @ai-contract: LogLine payloads are generated by the simulation engine (mock) or by OpenHands SDK stdout/stderr (real).
//               When the real backend is connected, each line arrives via WebSocket 'terminal:output' events.
//               The `id` is assigned by terminalStore — callers use appendLine(text, type) only.
export type LogLine = {
  id: string;
  text: string;
  type: LogLineType;
};

// @ai-contract: FileNode represents the virtual file tree shown in the FileExplorer.
//               In mock mode this tree is static (mockData.fileTree). In real mode it will be
//               populated from the OpenHands sandbox filesystem via WebSocket 'fs:tree' events.
//               The `language` field drives Monaco Editor syntax highlighting — must match Monaco language IDs.
export type FileNode = {
  id: string;
  name: string;
  type: 'file' | 'folder';
  language?: string;
  children?: FileNode[];
};

// @ai-contract: EditorTab represents an open file tab in the Monaco Editor panel.
//               Managed exclusively by fileStore (openFile / closeTab / setActiveTab).
//               The `modified` flag is set true by fileStore.updateFileContent and fileStore.setAIControlMode.
export type EditorTab = {
  id: string;
  name: string;
  modified?: boolean;
};

// @ai-contract: AgentStatuses is a flat record covering all three roles simultaneously.
//               Always contains all three keys — never partial. Managed by agentStore.
export type AgentStatuses = Record<AgentRole, AgentStatus>;

// @ai-contract: ActiveActivities stores the human-readable activity label shown in the UI
//               (e.g. "Rewriting Modal.tsx..."). Set alongside AgentStatus via agentStore.updateAgentStatus.
//               A null value means the agent has no current activity label (displayed as idle).
export type ActiveActivities = Record<AgentRole, string | null>;
