"""
Application settings loaded from environment variables / `.env` file.

All secrets (API keys, sandbox URLs) are server-side only — never exposed to the frontend.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict

_BACKEND_ROOT = Path(__file__).resolve().parents[1]


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=_BACKEND_ROOT / ".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # ─── Security (REQUIRED — no random fallback) ─────────────────────────
    # Both the API server and the background worker MUST share this secret
    # so JWT tokens generated by the worker are verifiable by the API.
    mcp_jwt_secret: str = ""
    api_key_secret: str = ""
    database_url: str = ""
    redis_url: str = "redis://localhost:6379/0"

    # OpenHands (legacy REST mode — kept for backward compat)
    openhands_api_url: str = "http://localhost:3000"
    openhands_api_key: str = ""

    # LLM (used by OpenHands SDK)
    llm_api_key: str = ""
    llm_model: str = "anthropic/claude-sonnet-4-5-20250929"
    llm_base_url: str = ""

    # Workspace
    workspace_dir: str = "./workspaces"

    # CORS
    cors_origins: str = "http://localhost:5173,http://127.0.0.1:5173"
    cors_origin_regex: str = r"^https?://(localhost|127\.0\.0\.1)(:\d+)?$"

    # Server
    host: str = "0.0.0.0"
    port: int = 8000

    def validate_required_secrets(self) -> None:
        """Raise at startup if critical secrets/runtime config are missing."""
        missing = [
            name
            for name, value in (
                ("MCP_JWT_SECRET", self.mcp_jwt_secret),
                ("API_KEY_SECRET", self.api_key_secret),
                ("DATABASE_URL", self.database_url),
                ("REDIS_URL", self.redis_url),
            )
            if not value
        ]
        if missing:
            raise RuntimeError(
                "FATAL: Missing required runtime configuration: "
                f"{', '.join(missing)}. Configure backend/.env so the API "
                "server and worker share the same PostgreSQL, Redis, Fernet, "
                "and MCP JWT settings."
            )

    @property
    def cors_origin_list(self) -> list[str]:
        return [o.strip() for o in self.cors_origins.split(",") if o.strip()]

    @property
    def workspace_path(self) -> Path:
        path = Path(self.workspace_dir)
        path.mkdir(parents=True, exist_ok=True)
        return path


@lru_cache
def get_settings() -> Settings:
    return Settings()
