"""
Application settings loaded from environment variables / `.env` file.

All secrets (API keys, sandbox URLs) are server-side only — never exposed to the frontend.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # ─── Security (REQUIRED — no random fallback) ─────────────────────────
    # Both the API server and the background worker MUST share this secret
    # so JWT tokens generated by the worker are verifiable by the API.
    mcp_jwt_secret: str = ""

    # OpenHands (legacy REST mode — kept for backward compat)
    openhands_api_url: str = "http://localhost:3000"
    openhands_api_key: str = ""

    # LLM (used by OpenHands SDK)
    llm_api_key: str = ""
    llm_model: str = "anthropic/claude-sonnet-4-5-20250929"
    llm_base_url: str = ""

    # Workspace
    workspace_dir: str = "./workspaces"

    # CORS
    cors_origins: str = "http://localhost:5173,http://127.0.0.1:5173"

    # Server
    host: str = "0.0.0.0"
    port: int = 8000

    def validate_required_secrets(self) -> None:
        """Raise at startup if critical secrets are missing."""
        if not self.mcp_jwt_secret:
            raise RuntimeError(
                "FATAL: MCP_JWT_SECRET environment variable is not set. "
                "Both the API server and the background worker MUST share "
                "the same secret. Add MCP_JWT_SECRET to your .env file."
            )

    @property
    def cors_origin_list(self) -> list[str]:
        return [o.strip() for o in self.cors_origins.split(",") if o.strip()]

    @property
    def workspace_path(self) -> Path:
        path = Path(self.workspace_dir)
        path.mkdir(parents=True, exist_ok=True)
        return path


@lru_cache
def get_settings() -> Settings:
    return Settings()
