"""
Dev Agent — Expert Developer Nanobot.

Responsibilities:
- Receives a user goal (or a QA defect report on retry)
- Inspects files via MCP read_file
- Writes/patches code via MCP write_file
- Operates EXCLUSIVELY through MCP tools (Rule 1: no local host tools)

The Dev agent is called by the orchestrator with either:
  1. The initial user goal string (first attempt)
  2. A structured QA defect report JSON (retry attempt)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .mcp_tools import mcp_exec, mcp_read_file, mcp_write_file

# ─── System Prompt ────────────────────────────────────────────────────────────

DEV_SYSTEM_PROMPT = """\
You are **Dev**, the expert developer in a multi-agent coding IDE.

## Your Role
You receive a coding goal from the orchestrator and implement it by reading,
writing, and patching files in the workspace. On retry, you receive a structured
QA defect report — you must fix the exact issues listed.

## Available Tools (MCP Facade)
You have three tools, all scoped to the current run's workspace:

1. **read_file(path)** → returns file content as a string
2. **write_file(path, content)** → writes/overwrites a file, returns success bool
3. **exec(command)** → runs a shell command, returns {exitCode, stdout, stderr, durationMs}

## Workflow
1. Analyze the goal or defect report.
2. Use `read_file` to inspect existing code.
3. Plan your changes (think step-by-step).
4. Use `write_file` to create or update files.
5. Optionally use `exec` to verify your changes compile/run.
6. Output a structured JSON summary of what you changed.

## Output Format
When you finish, output EXACTLY this JSON (no markdown fences, no extra text):
{
  "status": "done",
  "filesChanged": ["path/to/file1.py", "path/to/file2.ts"],
  "summary": "Brief description of what was implemented or fixed."
}

## Rules
- NEVER access the filesystem directly. Use ONLY the MCP tools.
- NEVER skip reading a file before modifying it — always inspect first.
- On retry with a QA report, fix EVERY issue in the report before finishing.
- Keep your changes minimal and focused on the goal.
"""

# ─── Agent Definition ─────────────────────────────────────────────────────────


@dataclass
class DevAgentConfig:
    """Configuration for the Dev agent."""

    system_prompt: str = DEV_SYSTEM_PROMPT
    model: str = ""  # Filled from settings at runtime
    max_iterations: int = 20
    name: str = "dev"
    label: str = "Dev"


@dataclass
class DevAgentResult:
    """Structured result from a Dev agent run."""

    status: str  # "done" | "error"
    files_changed: list[str] = field(default_factory=list)
    summary: str = ""
    raw_output: str = ""
    error: str | None = None


class DevAgent:
    """
    Dev agent that implements code changes via MCP tools.

    The agent is invoked by the orchestrator with a goal string.
    It uses the MCP tools to read/write files and execute commands.
    """

    def __init__(self, config: DevAgentConfig | None = None) -> None:
        self.config = config or DevAgentConfig()

    async def run(
        self,
        run_id: str,
        goal: str,
        context: dict[str, Any] | None = None,
    ) -> DevAgentResult:
        """
        Execute the Dev agent for a given goal.

        Args:
            run_id: The current run ID (used for MCP X-Run-Id scoping)
            goal: The user's goal or QA defect report JSON
            context: Optional additional context (workspace files, etc.)

        Returns:
            DevAgentResult with status, changed files, and summary.

        @ai-integration-point: Replace this stub with real LLM-backed agent
        execution via OpenHands SDK Conversation. The conversation should use
        the system prompt, receive the goal as the user message, and have
        MCP tools registered.
        """
        try:
            # ── Stub Implementation ─────────────────────────────────────
            # In production, this will be an OpenHands Conversation.
            # For now, we demonstrate the MCP tool chain end-to-end.

            ctx = context or {}
            task_id = ctx.get("task_id", "default")

            # 1. List what's in the workspace
            listing = await mcp_exec(run_id, "dir /b" if _is_windows() else "ls -la")

            # 2. Sanitize goal text for safe Python embedding
            safe_goal = goal.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")[:120]

            # 3. Generate a task-scoped filename
            file_name = f"{task_id}_impl.py"

            # 4. Write a valid Python stub
            stub_content = (
                "# Auto-generated by Dev agent\n"
                f"# Task ID: {task_id}\n\n\n"
                f"def main():\n"
                f"    '''Implement: {safe_goal}'''\n"
                f"    print('Done: {safe_goal}')\n\n\n"
                f"if __name__ == '__main__':\n"
                f"    main()\n"
            )
            await mcp_write_file(run_id, file_name, stub_content)

            return DevAgentResult(
                status="done",
                files_changed=[file_name],
                summary=f"Created {file_name}",
                raw_output=stub_content,
            )

        except Exception as e:
            return DevAgentResult(
                status="error",
                summary="Dev agent failed during execution.",
                error=str(e),
            )


def _is_windows() -> bool:
    import sys
    return sys.platform == "win32"
