"""
MCP tool helpers for Nanobot agents.

Each function calls the internal MCP facade at /internal/mcp/* endpoints
using httpx. Agents MUST ONLY use these tools — no local filesystem or shell
access (Rule 1).

Authentication: Uses JWT Bearer tokens generated by the run manager.
Falls back to X-Run-Id header if no token is available (dev compatibility).
"""

from __future__ import annotations

import httpx

from ..config import get_settings

_MCP_TIMEOUT = 60.0

# Per-run token store (set by the orchestrator before agent execution)
_run_tokens: dict[str, str] = {}


def set_run_token(run_id: str, token: str) -> None:
    """Register a JWT token for a run (called by the orchestrator)."""
    _run_tokens[run_id] = token


def clear_run_token(run_id: str) -> None:
    """Remove a run's token after completion."""
    _run_tokens.pop(run_id, None)


def _mcp_base_url() -> str:
    settings = get_settings()
    return f"http://127.0.0.1:{settings.port}/internal/mcp"


def _auth_headers(run_id: str) -> dict[str, str]:
    """Build auth headers: Bearer token is REQUIRED (no X-Run-Id fallback)."""
    token = _run_tokens.get(run_id)
    if not token:
        raise RuntimeError(
            f"No MCP JWT token registered for run '{run_id}'. "
            "The orchestrator must call set_run_token() before agent execution."
        )
    return {"Authorization": f"Bearer {token}"}


async def mcp_read_file(run_id: str, path: str) -> str:
    """Read a file from the run's workspace via MCP facade."""
    async with httpx.AsyncClient(timeout=_MCP_TIMEOUT) as client:
        resp = await client.post(
            f"{_mcp_base_url()}/read_file",
            headers=_auth_headers(run_id),
            json={"path": path},
        )
        resp.raise_for_status()
        return resp.json()["content"]


async def mcp_write_file(run_id: str, path: str, content: str) -> bool:
    """Write a file to the run's workspace via MCP facade."""
    async with httpx.AsyncClient(timeout=_MCP_TIMEOUT) as client:
        resp = await client.post(
            f"{_mcp_base_url()}/write_file",
            headers=_auth_headers(run_id),
            json={"path": path, "content": content},
        )
        resp.raise_for_status()
        return resp.json()["success"]


async def mcp_exec(
    run_id: str, command: str, cwd: str = "/workspace", agent_role: str = "dev",
) -> dict:
    """
    Execute a command in the run's workspace via MCP facade.

    Args:
        run_id: Run identifier for scoping
        command: Shell command to execute
        cwd: Working directory
        agent_role: "dev" or "qa" — used for command policy enforcement

    Returns: { "exitCode": int, "stdout": str, "stderr": str, "durationMs": int }
    """
    async with httpx.AsyncClient(timeout=_MCP_TIMEOUT) as client:
        resp = await client.post(
            f"{_mcp_base_url()}/exec",
            headers=_auth_headers(run_id),
            json={"command": command, "cwd": cwd, "agentRole": agent_role},
        )
        resp.raise_for_status()
        return resp.json()
